#include "Language.h"
#include <iostream>
#include <fstream>

void Language::LoadChinese() {
    std::unordered_map<std::string,std::string> zhStrings={
        // 应用程序消息
        {"app_start","Minecraft更新服务器启动"},
        {"app_stop","Minecraft更新服务器停止"},
        {"config_load","加载配置文件: "},
        {"config_missing","配置文件不存在，使用默认配置: "},
        {"directory_created","目录已创建"},
        {"scan_start","开始扫描工作目录: "},
        {"scan_complete","扫描完成"},
        {"scan_complete_files","扫描完成，找到 {} 个文件，{} 个目录"},
        {"package_building","构建更新包"},
        {"package_building_incremental","构建增量更新包: "},
        {"package_building_full","构建全量更新包: "},
        {"package_complete","更新包构建完成: "},
        {"diff_processing","处理文件差异"},
        {"diff_added","新增: "},
        {"error_version_format","版本号格式错误，必须为 x.x.x 格式"},
        {"error_version_order","版本顺序错误，必须从较低版本到较高版本"},
        {"error_package_exists","包已存在"},
        {"error_read_file","读取文件失败"},
        {"info_package_exists","包已存在，跳过创建"},
        {"info_incremental_package","增量包"},
        {"info_directory_package","目录包"},
        {"diff_modified","修改: "},
        {"diff_deleted","删除: "},
        {"diff_moved","移动: {} -> {}"},
        {"server_start","Web服务器启动"},
        {"server_start_at","Web服务器启动于 "},
        {"server_stop","Web服务器停止"},
        {"request_update","请求获取更新信息"},
        {"request_download","请求下载文件: "},
        {"request_package","请求下载更新包: "},

        // 错误消息
        {"error_config","配置错误: "},
        {"error_scan","扫描错误: "},
        {"error_package","打包错误: "},
        {"error_diff","差异计算错误: "},
        {"error_server","服务器错误: "},
        {"error_file_not_found","文件不存在: "},
        {"error_invalid_zip","无效的ZIP文件: "},
        {"error_io","I/O错误: "},
        {"error_time_conversion","时间转换错误: "},
        {"error_write_config","无法写入配置文件: "},
        {"error_create_directory","创建目录结构失败!"},
        {"error_open_file","无法打开文件: "},
        {"error_parse_json","解析JSON失败: "},
        {"error_init_version_manager","无法初始化版本管理器"},
        {"error_version_not_exist","版本不存在: "},
        {"error_version_snapshot_not_exist","版本快照不存在: "},
        {"error_save_snapshot","无法保存快照"},
        {"error_create_package","无法创建ZIP文件: "},
        {"error_zip_source","无法创建ZIP源"},
        {"error_add_file_zip","无法添加文件到ZIP: "},
        {"error_create_marker","无法创建空目录标记: "},
        {"error_no_versions","没有可用的版本"},
        {"error_open_package","无法打开包: "},
        {"error_zip_exists",".zip 已存在，将被覆盖"},
        {"error_delete_morefiles","无法删除多余的包文件: "},
        {"error_create_pathpackage","创建目录包失败: "},
        {"error_version_small","新版本号必须大于所有现有版本"},

        // 状态消息
        {"status_idle","空闲"},
        {"status_scanning","扫描中"},
        {"status_building","构建中"},
        {"status_serving","服务中"},

        // 通用消息
        {"info_zip_becreated",".zip 创建完成"},
        {"info_server_starting","正在启动Minecraft更新服务器..."},
        {"info_first_starting","这是第一个版本，只生成全量包"},
        {"info_workspace","工作空间: "},
        {"info_output_dir","输出目录: "},
        {"info_server_address","服务器地址: "},
        {"info_ctrl_c_stop","按 Ctrl+C 停止服务器"},
        {"info_scan_failed","扫描失败"},
        {"info_incremental_created","增量包 {} -> {} 创建完成!"},
        {"info_full_created","全量包 {} 创建完成!"},
        {"info_no_config","未找到配置文件，正在生成默认配置文件..."},
        {"info_default_config_created","默认配置文件已生成!"},
        {"info_put_game_files","请将游戏文件放入 'public' 文件夹中"},
        {"info_run_server","然后运行程序启动服务器"},
        {"info_enter_continue","按回车键继续..."},
        {"info_enter_exit","按回车键退出..."},
        {"info_enter_version","请输入版本号: "},
        {"info_enter_description","请输入版本描述 (可选，直接回车跳过): "},
        {"info_enter_from_version","请输入起始版本号: "},
        {"info_enter_to_version","请输入目标版本号: "},
        {"info_menu_choice","请选择操作 (1-8): "},
        {"info_invalid_choice","无效的选择，请重新输入。"},
        {"info_goodbye","感谢使用Minecraft更新服务器，再见!"},
        {"info_config_created","配置文件已创建"},
        {"info_directories_created","目录结构已创建"},
        {"info_version","版本 "},
        {"info_incremental","增量包 "},
        {"info_full","全量包 "},
        {"info_created_complete"," 创建完成!"},
        {"info_snapshot_saved","快照已保存: "},
        {"info_no_changes","没有变化，跳过增量包生成"},
        {"info_running","running"},
        {"info_file_not_found_simple","文件不存在"},
        {"info_directory_added","新增目录: "},
        {"info_directory_deleted","删除目录: "},
        {"info_moved","移动: "},
        {"info_to"," -> "},
        {"info_empty_directory","空目录"},
        {"info_delet_successed","已删除多余的目录包: "},
        {"info_createdpath_package","已生成目录包: "},
        {"info_rollback_part1","开始回退：从最新版本 "},
        {"info_rollback_part2"," 回退到目标版本 "},
        {"info_rollback_part3","，新版本号为 "},
        {"info_rollback_succed1","回退完成，新版本 " },
        {"info_rollback_succed2"," 已创建" }
    };
    strings["zh_CN"]=zhStrings;
}

void Language::LoadEnglish() {
    std::unordered_map<std::string,std::string> enStrings={
        {"app_start","Minecraft Update Server Starting"},
        {"app_stop","Minecraft Update Server Stopping"},
        {"config_load","Loading config file: "},
        {"config_missing","Config file not found, using default config: "},
        {"directory_created","Directory created"},
        {"scan_start","Start scanning workspace: "},
        {"scan_complete","Scan complete"},
        {"scan_complete_files","Scan complete, found {} files, {} directories"},
        {"package_building","Building update package"},
        {"package_building_incremental","Building incremental package: "},
        {"package_building_full","Building full package: "},
        {"package_complete","Package built: "},
        {"diff_processing","Processing file differences"},
        {"diff_added","Added: "},
        {"diff_modified","Modified: "},
        {"diff_deleted","Deleted: "},
        {"diff_moved","Moved: {} -> {}"},
        {"server_start","Web server starting"},
        {"server_start_at","Web server started at "},
        {"server_stop","Web server stopping"},
        {"request_update","Request for update info"},
        {"request_download","Request for file download: "},
        {"request_package","Request for package download: "},

        // Error messages
        {"error_config","Config error: "},
        {"error_scan","Scan error: "},
        {"error_package","Package error: "},
        {"error_diff","Diff error: "},
        {"error_server","Server error: "},
        {"error_file_not_found","File not found: "},
        {"error_invalid_zip","Invalid ZIP file: "},
        {"error_io","I/O error: "},
        {"error_time_conversion","Time conversion error: "},
        {"error_write_config","Cannot write config file: "},
        {"error_create_directory","Failed to create directory structure!"},
        {"error_open_file","Cannot open file: "},
        {"error_parse_json","Failed to parse JSON: "},
        {"error_init_version_manager","Cannot initialize version manager"},
        {"error_version_not_exist","Version does not exist: "},
        {"error_version_snapshot_not_exist","Version snapshot does not exist: "},
        {"error_save_snapshot","Cannot save snapshot"},
        {"error_create_package","Cannot create ZIP file: "},
        {"error_zip_source","Cannot create ZIP source"},
        {"error_add_file_zip","Cannot add file to ZIP: "},
        {"error_create_marker","Cannot create empty directory marker: "},
        {"error_no_versions","No versions available"},
        {"error_open_package","Cannot open package: "},
        {"error_zip_exists","The .zip file already exists and will be overwritten"},
        {"error_delete_morefiles","Failed to delete redundant package files: "},
        {"error_create_pathpackage","Failed to create directory package:  "},
        {"error_version_small","The new version number must be greater than all existing versions"},

        // Status messages
        {"status_idle","Idle"},
        {"status_scanning","Scanning"},
        {"status_building","Building"},
        {"status_serving","Serving"},

        // New error messages
        {"error_version_format","Version format error, must be x.x.x format"},
        {"error_version_order","Version order error, must be from lower to higher version"},
        {"error_package_exists","Package already exists"},
        {"error_read_file","Failed to read file"},

        // New info messages
        {"info_package_exists","Package exists, skipping creation"},
        {"info_incremental_package","Incremental package"},
        {"info_directory_package","Directory package"},
        // General messages
        {"info_zip_becreated","The .zip file has been created"},
        {"info_server_starting","Starting Minecraft Update Server..."},
        {"info_first_starting","This is the first package,only seed full-package"},
        {"info_workspace","Workspace: "},
        {"info_output_dir","Output directory: "},
        {"info_server_address","Server address: "},
        {"info_ctrl_c_stop","Press Ctrl+C to stop server"},
        {"info_scan_failed","Scan failed"},
        {"info_incremental_created","Incremental package {} -> {} created!"},
        {"info_full_created","Full package {} created!"},
        {"info_no_config","Config file not found, generating default config..."},
        {"info_default_config_created","Default config file created!"},
        {"info_put_game_files","Please put game files in 'public' folder"},
        {"info_run_server","Then run program to start server"},
        {"info_enter_continue","Press Enter to continue..."},
        {"info_enter_exit","Press Enter to exit..."},
        {"info_enter_version","Enter version: "},
        {"info_enter_description","Enter description (optional, press Enter to skip): "},
        {"info_enter_from_version","Enter source version: "},
        {"info_enter_to_version","Enter target version: "},
        {"info_menu_choice","Select operation (1-8): "},
        {"info_invalid_choice","Invalid choice, please re-enter."},
        {"info_goodbye","Thank you for using Minecraft Update Server, goodbye!"},
        {"info_config_created","Config file created"},
        {"info_directories_created","Directory structure created"},
        {"info_version","Version "},
        {"info_incremental","Incremental package "},
        {"info_full","Full package "},
        {"info_created_complete"," created!"},
        {"info_snapshot_saved","Snapshot saved: "},
        {"info_no_changes","No changes, skip incremental package generation"},
        {"info_running","running"},
        {"info_file_not_found_simple","File not found"},
        {"info_directory_added","Directory added: "},
        {"info_directory_deleted","Directory deleted: "},
        {"info_moved","Moved: "},
        {"info_to"," -> "},
        {"info_empty_directory","Empty directory"},
        {"info_delet_successed","Excess directory packages have been deleted: " },
        {"info_createdpath_package","The directory package has been generated: "},
        {"info_rollback_part1","Starting rollback: from the latest version "},
        {"info_rollback_part2"," Go back to the target version " },
        {"info_rollback_part3",",The new version number is "},
        {"info_rollback_succed1","Rollback completed, new version " },
        {"info_rollback_succed2"," has been created"}
    };
    strings["en_US"]=enStrings;
}